### ISSUE TITLE
'code' is an undefined name in detect_waf.py

### ISSUE THREAD

**Issue by cclauss** [YagamiiLight/Cerberus#2]
https://github.com/YagamiiLight/Cerberus/blob/master/strike/detect_waf.py#L44

**Comment by YagamiiLight** [comment]
> https://github.com/YagamiiLight/Cerberus/blob/master/strike/detect_waf.py#L44

你好！sorry，push错了没完成调试的代码，最新的已经push，问题已解决，感谢您的反馈！
